[package]
name = "hardware-synth-interface"
version = "0.1.0"
edition = "2024"
authors = ["Riley Lundquist"]
license = "MIT"

[dependencies]
cortex-m = { version = "0.7.8", features = [
    "inline-asm",
    "critical-section-single-core",
] }
cortex-m-rt = { version = "0.7.6", features = ["device", "set-vtor", "set-sp"] }
daisy-embassy = { version = "0.3.0", features = ["seed3"] }
defmt-serial = "0.14.0"
emballoc = "0.3.0"
embassy-executor = { version = "0.10.0", features = [
    "platform-cortex-m",
    "executor-thread",
    "executor-interrupt",
    "defmt",
] }
embassy-futures = { version = "0.1.2" }
embassy-stm32 = { version = "0.6.0", features = [
    "defmt",
    "stm32h750ib",
    "time-driver-tim5",
    "exti",
    "memory-x",
    "unstable-pac",
    "chrono",
] }
embassy-sync = { version = "0.8.0", features = ["defmt"] }
embassy-time = { version = "0.5.1", features = [
    "defmt",
    "defmt-timestamp-uptime",
    "tick-hz-32_768",
    "generic-queue-8",
] }
embedded-graphics = "0.8.2"
heapless = "0.9.3"
logger = { path = "../logger" }
rust-tinyusb-host = { git = "https://github.com/rlundquist3/rust-tinyusb-host.git", rev = "2e15a2f" }
ssd1306 = "0.10.0"
static_cell = "2.1.1"
synth-core = { path = "../synth-core" }
synth-gui = { path = "../synth-gui" }
